
name: "Python Codecov Action"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "An action to upload coverage to codecov.io for Python package by using Poetry. Requires poetry to be installed"
branding:
  icon: "package"
  color: "green"
runs:
  using: "composite"
  steps:
    - run: poetry run install codecov
      shell: bash
      name: Install codecov-python
      working-directory: ${{ github.workspace }}
    - run: echo "Running coverage"
      shell: bash
    - run: poetry run coverage run -m unittest
      shell: bash
      name: Run unit tests with coverage
      working-directory: ${{ github.workspace }}
    - run: echo "Uploading to codecov.io"
      shell: bash
    - run: poetry run codecov
      shell: bash
      name: Upload coverage to codecov.io
      working-directory: ${{ github.workspace }}
