
name: "Python Codecov Action"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "An action to upload coverage to codecov.io for Python package by using Poetry. Requires poetry to be installed"
inputs:
  test-command:
    description: "Command to run the tests"
    required: true
    default: "-m unittest"
branding:
  icon: "package"
  color: "green"
runs:
  using: "composite"
  steps:
    - run: poetry run python -m pip install codecov
      shell: bash
      name: Install codecov-python
      working-directory: ${{ github.workspace }}
    - run: poetry run coverage run ${{ inputs.test-command }}
      shell: bash
      name: Run unit tests with coverage
      working-directory: ${{ github.workspace }}
    - run: poetry run codecov
      shell: bash
      name: Upload coverage to codecov.io
      working-directory: ${{ github.workspace }}
