name: 'Build XML documentation and upload coverage'
author: "Jaspar Löchte <jaspar.loechte@greenbone.net>"
description: 'An action to upload documentation coverage to codecov.io for C Lang repository. Requires to run with the greenbone/doxygen docker image.'
branding:
  icon: "package"
  color: "green"
runs:
  using: "composite"
  steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Install coverxygen and codecov
      run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install setuptools --upgrade
          pip install 'coverxygen>=1.3.1' codecov
    - name: Generate documentation (XML)
      run: |
        mkdir build
        cd build
        cmake -DSKIP_SRC=1 ..
        make doc-xml
    - name: Establish documentation coverage
      run: |
          . .venv/bin/activate
          python -m coverxygen --src-dir ${{ github.workspace }} \
          --xml-dir build/doc/generated/xml/ --output lcov.info
    - uses: codecov/codecov-action@v1
      with:
        files: lcov.info