
name: "Python Poetry Action"
author: "Björn Ricks <bjoern.ricks@greenbone.net>"
description: "An action to install Python dependencies via poetry"
branding:
  icon: "package"
  color: "green"
runs:
  using: "composite"
  steps:
    - run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry
      shell: bash
      name: Install poetry
    - run: poetry install
      shell: bash
      name: Install dependencies
