name: Test Actions

on:
  push:
    tags: ["*"]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test reference branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        uses: ./reference-version
      - name: Show output
        run: |
          echo "Current Branch: ${{ env.VERSION }}"
