name: Test Release Actions

on:
  push:
    tags: ["*"]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    name: Test Release Patch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run release patch actions
        uses: ./release-patch
        with:
          github-user: foo
          github-user-email: foo@bar.baz
          github-user-token: bar
          gpg-key: boo
          gpg-passphrase: foo
          gpg-fingerprint: baz