name: Test Python Actions

on:
  push:
    tags: ["*"]
    branches: [main]
    paths-ignore:
      - 'artifacts-download-trigger/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'artifacts-download-trigger/**'

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    name: Install poetry
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install poetry
        uses: ./poetry
        with:
          version: ${{ matrix.python-version }}
        continue-on-error: true
      - run: poetry

  test-coverage:
    runs-on: ubuntu-latest
    name: Test Coverage Python
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install poetry
        uses: ./coverage-python
        with:
          version: ${{ matrix.python-version }}
        continue-on-error: true
      - run: poetry

  test-linting:
    runs-on: ubuntu-latest
    name: Test Linting Python
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install poetry
        uses: ./lint-python
        with:
          version: ${{ matrix.python-version }}
        continue-on-error: true
      - run: poetry
