name: Test Actions

on:
  push:
    tags: ["*"]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-reference-version-branch:
    runs-on: ubuntu-latest
    name: Test reference branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        uses: ./reference-version
      - name: Checkout assert.sh
        uses: actions/checkout@v2
        with:
          repository: torokmark/assert.sh
      - name: Show & assert output
        run: |
          echo "Current Branch: ${{ env.VERSION }}"
          source 'assert.sh'
          assert_eq ${{ env.VERSION }} "main" "not equivalent!"
  test-reference-version-no-tag:
    runs-on: ubuntu-latest
    name: Test branch is not a tag
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        uses: ./reference-version
        with:
          strip-tag-prefix: m
      - name: Checkout assert.sh
        uses: actions/checkout@v2
        with:
          repository: torokmark/assert.sh
      - name: Show & assert output
        run: |
          echo "Current Branch: ${{ env.VERSION }}"
          source 'assert.sh'
          assert_eq ${{ env.VERSION }} "main" "not equivalent!"

  test-container-image-tags-branch:
    runs-on: ubuntu-latest
    name: Test reference branch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        id: container
        uses: ./container-image-tags
      - name: Checkout assert.sh
        uses: actions/checkout@v2
        with:
          repository: torokmark/assert.sh
      - name: Show & assert output
        run: |
          echo "Image tags: ${{ steps.container.outputs.image-tags }}"
          source 'assert.sh'
          assert_eq ${{ steps.container.outputs.image-tags }} "greenbone/actions:unstable" "wrong container tag"
