name: Test Release Actions

on:
  push:
    tags: ["*"]
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-poetry:
    runs-on: ubuntu-latest
    name: Test Release Patch
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run release patch actions
        uses: ./release-patch